package hql.common.beans;

// Generated 2015-11-2 0:52:26 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TFourDefaultOdds generated by hbm2java
 */
public class TFourDefaultOdds implements java.io.Serializable {

	private Integer fourDefaultOddsId;
	private Integer playId;
	private String playName;
	private BigDecimal defaultOdds;
	private Set TFourNumbers = new HashSet(0);

	public TFourDefaultOdds() {
	}

	public TFourDefaultOdds(Integer playId, String playName,
			BigDecimal defaultOdds, Set TFourNumbers) {
		this.playId = playId;
		this.playName = playName;
		this.defaultOdds = defaultOdds;
		this.TFourNumbers = TFourNumbers;
	}

	public Integer getFourDefaultOddsId() {
		return this.fourDefaultOddsId;
	}

	public void setFourDefaultOddsId(Integer fourDefaultOddsId) {
		this.fourDefaultOddsId = fourDefaultOddsId;
	}

	public Integer getPlayId() {
		return this.playId;
	}

	public void setPlayId(Integer playId) {
		this.playId = playId;
	}

	public String getPlayName() {
		return this.playName;
	}

	public void setPlayName(String playName) {
		this.playName = playName;
	}

	public BigDecimal getDefaultOdds() {
		return this.defaultOdds;
	}

	public void setDefaultOdds(BigDecimal defaultOdds) {
		this.defaultOdds = defaultOdds;
	}

	public Set getTFourNumbers() {
		return this.TFourNumbers;
	}

	public void setTFourNumbers(Set TFourNumbers) {
		this.TFourNumbers = TFourNumbers;
	}

}
