package hql.common.beans;

// Generated 2015-11-2 0:52:26 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TFourNumber generated by hbm2java
 */
public class TFourNumber implements java.io.Serializable {

	private Integer fourNumberId;
	private TFourDefaultOdds TFourDefaultOdds;
	private String numberName;
	private BigDecimal currentOdds;
	private BigDecimal defaultOdds;

	public TFourNumber() {
	}

	public TFourNumber(TFourDefaultOdds TFourDefaultOdds, String numberName,
			BigDecimal currentOdds, BigDecimal defaultOdds) {
		this.TFourDefaultOdds = TFourDefaultOdds;
		this.numberName = numberName;
		this.currentOdds = currentOdds;
		this.defaultOdds = defaultOdds;
	}

	public Integer getFourNumberId() {
		return this.fourNumberId;
	}

	public void setFourNumberId(Integer fourNumberId) {
		this.fourNumberId = fourNumberId;
	}

	public TFourDefaultOdds getTFourDefaultOdds() {
		return this.TFourDefaultOdds;
	}

	public void setTFourDefaultOdds(TFourDefaultOdds TFourDefaultOdds) {
		this.TFourDefaultOdds = TFourDefaultOdds;
	}

	public String getNumberName() {
		return this.numberName;
	}

	public void setNumberName(String numberName) {
		this.numberName = numberName;
	}

	public BigDecimal getCurrentOdds() {
		return this.currentOdds;
	}

	public void setCurrentOdds(BigDecimal currentOdds) {
		this.currentOdds = currentOdds;
	}

	public BigDecimal getDefaultOdds() {
		return this.defaultOdds;
	}

	public void setDefaultOdds(BigDecimal defaultOdds) {
		this.defaultOdds = defaultOdds;
	}

}
