package hql.common.beans;

// Generated 2015-11-2 0:52:26 by Hibernate Tools 4.0.0

/**
 * TLogDetail generated by hbm2java
 */
public class TLogDetail implements java.io.Serializable {

	private Integer logDetailId;
	private TLog TLog;
	private String logDetail;
	private Short detailType;

	public TLogDetail() {
	}

	public TLogDetail(TLog TLog, String logDetail, Short detailType) {
		this.TLog = TLog;
		this.logDetail = logDetail;
		this.detailType = detailType;
	}

	public Integer getLogDetailId() {
		return this.logDetailId;
	}

	public void setLogDetailId(Integer logDetailId) {
		this.logDetailId = logDetailId;
	}

	public TLog getTLog() {
		return this.TLog;
	}

	public void setTLog(TLog TLog) {
		this.TLog = TLog;
	}

	public String getLogDetail() {
		return this.logDetail;
	}

	public void setLogDetail(String logDetail) {
		this.logDetail = logDetail;
	}

	public Short getDetailType() {
		return this.detailType;
	}

	public void setDetailType(Short detailType) {
		this.detailType = detailType;
	}

}
