package hql.common.beans;

// Generated 2015-11-2 0:52:26 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TLog generated by hbm2java
 */
public class TLog implements java.io.Serializable {

	private Integer logId;
	private Integer logOperaUserId;
	private Integer logBeOperaUserId;
	private Date logOperaTime;
	private String operaIp;
	private Short isLeapfrogOpera;
	private Set TLogDetails = new HashSet(0);

	public TLog() {
	}

	public TLog(Date logOperaTime) {
		this.logOperaTime = logOperaTime;
	}

	public TLog(Integer logOperaUserId, Integer logBeOperaUserId,
			Date logOperaTime, String operaIp, Short isLeapfrogOpera,
			Set TLogDetails) {
		this.logOperaUserId = logOperaUserId;
		this.logBeOperaUserId = logBeOperaUserId;
		this.logOperaTime = logOperaTime;
		this.operaIp = operaIp;
		this.isLeapfrogOpera = isLeapfrogOpera;
		this.TLogDetails = TLogDetails;
	}

	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	public Integer getLogOperaUserId() {
		return this.logOperaUserId;
	}

	public void setLogOperaUserId(Integer logOperaUserId) {
		this.logOperaUserId = logOperaUserId;
	}

	public Integer getLogBeOperaUserId() {
		return this.logBeOperaUserId;
	}

	public void setLogBeOperaUserId(Integer logBeOperaUserId) {
		this.logBeOperaUserId = logBeOperaUserId;
	}

	public Date getLogOperaTime() {
		return this.logOperaTime;
	}

	public void setLogOperaTime(Date logOperaTime) {
		this.logOperaTime = logOperaTime;
	}

	public String getOperaIp() {
		return this.operaIp;
	}

	public void setOperaIp(String operaIp) {
		this.operaIp = operaIp;
	}

	public Short getIsLeapfrogOpera() {
		return this.isLeapfrogOpera;
	}

	public void setIsLeapfrogOpera(Short isLeapfrogOpera) {
		this.isLeapfrogOpera = isLeapfrogOpera;
	}

	public Set getTLogDetails() {
		return this.TLogDetails;
	}

	public void setTLogDetails(Set TLogDetails) {
		this.TLogDetails = TLogDetails;
	}

}
