package hql.common.beans;

// Generated 2015-11-2 0:52:26 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TMakeWater generated by hbm2java
 */
public class TMakeWater implements java.io.Serializable {

	private Integer makeWaterId;
	private TUser TUser;
	private Integer parentUserId;
	private BigDecimal makeWaterValue;
	private Integer palyGroupId;

	public TMakeWater() {
	}

	public TMakeWater(TUser TUser, Integer parentUserId,
			BigDecimal makeWaterValue, Integer palyGroupId) {
		this.TUser = TUser;
		this.parentUserId = parentUserId;
		this.makeWaterValue = makeWaterValue;
		this.palyGroupId = palyGroupId;
	}

	public Integer getMakeWaterId() {
		return this.makeWaterId;
	}

	public void setMakeWaterId(Integer makeWaterId) {
		this.makeWaterId = makeWaterId;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public Integer getParentUserId() {
		return this.parentUserId;
	}

	public void setParentUserId(Integer parentUserId) {
		this.parentUserId = parentUserId;
	}

	public BigDecimal getMakeWaterValue() {
		return this.makeWaterValue;
	}

	public void setMakeWaterValue(BigDecimal makeWaterValue) {
		this.makeWaterValue = makeWaterValue;
	}

	public Integer getPalyGroupId() {
		return this.palyGroupId;
	}

	public void setPalyGroupId(Integer palyGroupId) {
		this.palyGroupId = palyGroupId;
	}

}
