package hql.common.beans;

// Generated 2015-11-2 0:52:26 by Hibernate Tools 4.0.0

/**
 * TMsgPush generated by hbm2java
 */
public class TMsgPush implements java.io.Serializable {

	private Integer msgPushId;
	private Integer pushContent;

	public TMsgPush() {
	}

	public TMsgPush(Integer pushContent) {
		this.pushContent = pushContent;
	}

	public Integer getMsgPushId() {
		return this.msgPushId;
	}

	public void setMsgPushId(Integer msgPushId) {
		this.msgPushId = msgPushId;
	}

	public Integer getPushContent() {
		return this.pushContent;
	}

	public void setPushContent(Integer pushContent) {
		this.pushContent = pushContent;
	}

}
