package hql.common.beans;

// Generated 2015-11-2 0:52:26 by Hibernate Tools 4.0.0

/**
 * TNotice generated by hbm2java
 */
public class TNotice implements java.io.Serializable {

	private Integer noticeId;
	private String noticeContent;

	public TNotice() {
	}

	public TNotice(String noticeContent) {
		this.noticeContent = noticeContent;
	}

	public Integer getNoticeId() {
		return this.noticeId;
	}

	public void setNoticeId(Integer noticeId) {
		this.noticeId = noticeId;
	}

	public String getNoticeContent() {
		return this.noticeContent;
	}

	public void setNoticeContent(String noticeContent) {
		this.noticeContent = noticeContent;
	}

}
