package hql.common.beans;

// Generated 2015-11-2 0:52:26 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TRes generated by hbm2java
 */
public class TRes implements java.io.Serializable {

	private Integer resId;
	private String resName;
	private String resAlias;
	private Integer resSn;
	private Integer resParentId;
	private String resDefaultAddress;
	private String resPath;
	private Set TRoleReses = new HashSet(0);

	public TRes() {
	}

	public TRes(String resName, String resAlias, Integer resSn,
			Integer resParentId, String resDefaultAddress, String resPath,
			Set TRoleReses) {
		this.resName = resName;
		this.resAlias = resAlias;
		this.resSn = resSn;
		this.resParentId = resParentId;
		this.resDefaultAddress = resDefaultAddress;
		this.resPath = resPath;
		this.TRoleReses = TRoleReses;
	}

	public Integer getResId() {
		return this.resId;
	}

	public void setResId(Integer resId) {
		this.resId = resId;
	}

	public String getResName() {
		return this.resName;
	}

	public void setResName(String resName) {
		this.resName = resName;
	}

	public String getResAlias() {
		return this.resAlias;
	}

	public void setResAlias(String resAlias) {
		this.resAlias = resAlias;
	}

	public Integer getResSn() {
		return this.resSn;
	}

	public void setResSn(Integer resSn) {
		this.resSn = resSn;
	}

	public Integer getResParentId() {
		return this.resParentId;
	}

	public void setResParentId(Integer resParentId) {
		this.resParentId = resParentId;
	}

	public String getResDefaultAddress() {
		return this.resDefaultAddress;
	}

	public void setResDefaultAddress(String resDefaultAddress) {
		this.resDefaultAddress = resDefaultAddress;
	}

	public String getResPath() {
		return this.resPath;
	}

	public void setResPath(String resPath) {
		this.resPath = resPath;
	}

	public Set getTRoleReses() {
		return this.TRoleReses;
	}

	public void setTRoleReses(Set TRoleReses) {
		this.TRoleReses = TRoleReses;
	}

}
