package hql.common.beans;

// Generated 2015-11-2 0:52:26 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TRole generated by hbm2java
 */
public class TRole implements java.io.Serializable {

	private int roleId;
	private String roleName;
	private String roleAlias;
	private String roleNote;
	private Short allowDel;
	private Short allowEdit;
	private Short roleEnabled;
	private Set TRoleReses = new HashSet(0);
	private Set TUserRoles = new HashSet(0);

	public TRole() {
	}

	public TRole(int roleId, String roleName) {
		this.roleId = roleId;
		this.roleName = roleName;
	}

	public TRole(int roleId, String roleName, String roleAlias,
			String roleNote, Short allowDel, Short allowEdit,
			Short roleEnabled, Set TRoleReses, Set TUserRoles) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleAlias = roleAlias;
		this.roleNote = roleNote;
		this.allowDel = allowDel;
		this.allowEdit = allowEdit;
		this.roleEnabled = roleEnabled;
		this.TRoleReses = TRoleReses;
		this.TUserRoles = TUserRoles;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleAlias() {
		return this.roleAlias;
	}

	public void setRoleAlias(String roleAlias) {
		this.roleAlias = roleAlias;
	}

	public String getRoleNote() {
		return this.roleNote;
	}

	public void setRoleNote(String roleNote) {
		this.roleNote = roleNote;
	}

	public Short getAllowDel() {
		return this.allowDel;
	}

	public void setAllowDel(Short allowDel) {
		this.allowDel = allowDel;
	}

	public Short getAllowEdit() {
		return this.allowEdit;
	}

	public void setAllowEdit(Short allowEdit) {
		this.allowEdit = allowEdit;
	}

	public Short getRoleEnabled() {
		return this.roleEnabled;
	}

	public void setRoleEnabled(Short roleEnabled) {
		this.roleEnabled = roleEnabled;
	}

	public Set getTRoleReses() {
		return this.TRoleReses;
	}

	public void setTRoleReses(Set TRoleReses) {
		this.TRoleReses = TRoleReses;
	}

	public Set getTUserRoles() {
		return this.TUserRoles;
	}

	public void setTUserRoles(Set TUserRoles) {
		this.TUserRoles = TUserRoles;
	}

}
