package hql.common.beans;

// Generated 2015-11-2 0:52:26 by Hibernate Tools 4.0.0

/**
 * TRoleRes generated by hbm2java
 */
public class TRoleRes implements java.io.Serializable {

	private Integer roleResId;
	private TRole TRole;
	private TRes TRes;

	public TRoleRes() {
	}

	public TRoleRes(TRole TRole, TRes TRes) {
		this.TRole = TRole;
		this.TRes = TRes;
	}

	public Integer getRoleResId() {
		return this.roleResId;
	}

	public void setRoleResId(Integer roleResId) {
		this.roleResId = roleResId;
	}

	public TRole getTRole() {
		return this.TRole;
	}

	public void setTRole(TRole TRole) {
		this.TRole = TRole;
	}

	public TRes getTRes() {
		return this.TRes;
	}

	public void setTRes(TRes TRes) {
		this.TRes = TRes;
	}

}
