package hql.common.beans;

// Generated 2015-11-2 0:52:26 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TThreeNumber generated by hbm2java
 */
public class TThreeNumber implements java.io.Serializable {

	private Integer threeNumberId;
	private TThreeDefaultOdds TThreeDefaultOdds;
	private String numberName;
	private BigDecimal currentOdds;
	private BigDecimal defaultOdds;

	public TThreeNumber() {
	}

	public TThreeNumber(TThreeDefaultOdds TThreeDefaultOdds, String numberName,
			BigDecimal currentOdds, BigDecimal defaultOdds) {
		this.TThreeDefaultOdds = TThreeDefaultOdds;
		this.numberName = numberName;
		this.currentOdds = currentOdds;
		this.defaultOdds = defaultOdds;
	}

	public Integer getThreeNumberId() {
		return this.threeNumberId;
	}

	public void setThreeNumberId(Integer threeNumberId) {
		this.threeNumberId = threeNumberId;
	}

	public TThreeDefaultOdds getTThreeDefaultOdds() {
		return this.TThreeDefaultOdds;
	}

	public void setTThreeDefaultOdds(TThreeDefaultOdds TThreeDefaultOdds) {
		this.TThreeDefaultOdds = TThreeDefaultOdds;
	}

	public String getNumberName() {
		return this.numberName;
	}

	public void setNumberName(String numberName) {
		this.numberName = numberName;
	}

	public BigDecimal getCurrentOdds() {
		return this.currentOdds;
	}

	public void setCurrentOdds(BigDecimal currentOdds) {
		this.currentOdds = currentOdds;
	}

	public BigDecimal getDefaultOdds() {
		return this.defaultOdds;
	}

	public void setDefaultOdds(BigDecimal defaultOdds) {
		this.defaultOdds = defaultOdds;
	}

}
