package hql.common.beans;

// Generated 2015-11-2 0:52:26 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TTwoNumber generated by hbm2java
 */
public class TTwoNumber implements java.io.Serializable {

	private Integer twoNumberId;
	private TTwoDefaultOdds TTwoDefaultOdds;
	private String numberName;
	private BigDecimal currentOdds;
	private BigDecimal defaultOdds;

	public TTwoNumber() {
	}

	public TTwoNumber(TTwoDefaultOdds TTwoDefaultOdds, String numberName,
			BigDecimal currentOdds, BigDecimal defaultOdds) {
		this.TTwoDefaultOdds = TTwoDefaultOdds;
		this.numberName = numberName;
		this.currentOdds = currentOdds;
		this.defaultOdds = defaultOdds;
	}

	public Integer getTwoNumberId() {
		return this.twoNumberId;
	}

	public void setTwoNumberId(Integer twoNumberId) {
		this.twoNumberId = twoNumberId;
	}

	public TTwoDefaultOdds getTTwoDefaultOdds() {
		return this.TTwoDefaultOdds;
	}

	public void setTTwoDefaultOdds(TTwoDefaultOdds TTwoDefaultOdds) {
		this.TTwoDefaultOdds = TTwoDefaultOdds;
	}

	public String getNumberName() {
		return this.numberName;
	}

	public void setNumberName(String numberName) {
		this.numberName = numberName;
	}

	public BigDecimal getCurrentOdds() {
		return this.currentOdds;
	}

	public void setCurrentOdds(BigDecimal currentOdds) {
		this.currentOdds = currentOdds;
	}

	public BigDecimal getDefaultOdds() {
		return this.defaultOdds;
	}

	public void setDefaultOdds(BigDecimal defaultOdds) {
		this.defaultOdds = defaultOdds;
	}

}
