package hql.common.beans;

// Generated 2015-11-2 0:52:26 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TUserRole generated by hbm2java
 */
public class TUserRole implements java.io.Serializable {

	private Integer userRoleId;
	private TUser TUser;
	private TRole TRole;
	private BigDecimal parentPercentMax;
	private BigDecimal percentMax;
	private Integer parentId;

	public TUserRole() {
	}

	public TUserRole(TUser TUser, TRole TRole, BigDecimal parentPercentMax,
			BigDecimal percentMax, Integer parentId) {
		this.TUser = TUser;
		this.TRole = TRole;
		this.parentPercentMax = parentPercentMax;
		this.percentMax = percentMax;
		this.parentId = parentId;
	}

	public Integer getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Integer userRoleId) {
		this.userRoleId = userRoleId;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public TRole getTRole() {
		return this.TRole;
	}

	public void setTRole(TRole TRole) {
		this.TRole = TRole;
	}

	public BigDecimal getParentPercentMax() {
		return this.parentPercentMax;
	}

	public void setParentPercentMax(BigDecimal parentPercentMax) {
		this.parentPercentMax = parentPercentMax;
	}

	public BigDecimal getPercentMax() {
		return this.percentMax;
	}

	public void setPercentMax(BigDecimal percentMax) {
		this.percentMax = percentMax;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

}
